from repositories.base_repository import BaseRepository
from repositories.user_repository import UserRepository
from repositories.employee_repository import EmployeeRepository
from repositories.department_repository import DepartmentRepository
from repositories.attendance_repository import AttendanceRepository
from repositories.leave_repository import LeaveRepository
from repositories.activity_log_repository import ActivityLogRepository
